@echo off
setlocal
REM One-click generator for images\manifest.json
REM Place this .bat in the repo ROOT (same folder as index.html and \images\)

set "SCRIPT_DIR=%~dp0"
set "PS1=%SCRIPT_DIR%generate_manifest.ps1"

REM Write the PowerShell script next to the BAT if it doesn't exist
if not exist "%PS1%" (
  >"%PS1%" (
    echo # Autogenerated by generate_manifest.bat
    echo param(^
    echo   [string]$Root = "$(Join-Path $PSScriptRoot 'images')"^
    echo ^)
    echo $ErrorActionPreference = "Stop"
    echo if (-not (Test-Path $Root)) { Write-Error "Images folder not found: $Root" }
    echo $exts = @('.jpg','.jpeg','.png','.webp','.gif')
    echo $maps = [ordered]@{}
    echo Get-ChildItem -Path $Root -Directory ^| Sort-Object Name ^| ForEach-Object {
    echo ^  $mapName = $_.Name
    echo ^  $files = Get-ChildItem -Path $_.FullName -File ^| Where-Object { $exts -contains $_.Extension.ToLower() } ^| Sort-Object Name ^| Select-Object -ExpandProperty Name
    echo ^  if ($files.Count -gt 0) { $maps[$mapName] = $files }
    echo }
    echo $data = [ordered]@{ maps = $maps }
    echo $dest = Join-Path $Root 'manifest.json'
    echo $data ^| ConvertTo-Json -Depth 10 ^| Out-File -FilePath $dest -Encoding UTF8
    echo Write-Host "Wrote $dest"
  )
)

powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%"
echo.
pause
